import React, { useMemo } from 'react';

import StringInput from './StringInput';
import MenuInput from './MenuInput';
import { countries } from './CountryInput';

const states = {
  ar: [
    'Capital Federal',
    'Buenos Aires',
    'Catamarca',
    'Córdoba',
    'Corrientes',
    'Entre Rios',
    'Jujuy',
    'Mendoza',
    'La Rioja',
    'Salta',
    'San Juan',
    'San Luis',
    'Santa Fé',
    'Santiago del Estero',
    'Tucumán',
    'Chaco',
    'Chubut',
    'Formosa',
    'Misiones',
    'Neuquen',
    'La Pampa',
    'Rio Negro',
    'Santa Cruz',
    'Tierra de Fuego',
  ],

  at: [
    ['B', 'Burgenland'],
    ['K', 'Carinthia'],
    ['NÖ', 'Lower Austria'],
    ['OÖ', 'Upper Austria'],
    ['S', 'Salzburg'],
    ['ST', 'Styria'],
    ['T', 'Tyrol'],
    ['V', 'Vorarlberg'],
    ['W', 'Vienna'],
  ],

  au: [
    ['ACT', 'Aust Capital Terr'],
    ['NSW', 'New South Wales'],
    ['NT', 'Northern Territory'],
    ['QLD', 'Queensland'],
    ['SA', 'South Australia'],
    ['TAS', 'Tasmania'],
    ['VIC', 'Victoria'],
    ['WA', 'Western Australia'],
  ],

  be: [
    'Antwerp',
    'Brabant (Flemish)',
    'Hainaut',
    'Liege',
    'Limburg',
    'Luxembourg',
    'Namur',
    'Oost-Vlaanderen',
    'West-Vlaanderen',
    'Brabant (Walloon)',
    'Brussels (Capital)',
  ],

  bg: [
    'Burgas',
    'Grad Sofiya',
    'Khaskovo',
    'Lovech',
    'Montana',
    'Plovdiv',
    'Ruse',
    'Sofiya',
    'Varna',
  ],

  br: [
    ['AC', 'Acre'],
    ['AL', 'Alagoas'],
    ['AM', 'Amazon'],
    ['AP', 'Amapá'],
    ['BA', 'Bahia'],
    ['CE', 'Ceará'],
    ['DF', 'Brasília'],
    ['ES', 'Espírito Santo'],
    ['GO', 'Goiás'],
    ['MA', 'Maranhão'],
    ['MG', 'Minas Gerais'],
    ['MS', 'Mato Grosso do Sul'],
    ['MT', 'Mato Grosso'],
    ['PA', 'Pará'],
    ['PB', 'Paraíba'],
    ['PE', 'Pernambuco'],
    ['PI', 'Piauí'],
    ['PR', 'Paraná'],
    ['RJ', 'Rio de Janeiro'],
    ['RN', 'Rio Grande do Norte'],
    ['RO', 'Rondônia'],
    ['RR', 'Roraima'],
    ['RS', 'Rio Grande do Sul'],
    ['SC', 'Santa Catarina'],
    ['SE', 'Sergipe'],
    ['SP', 'São Paulo'],
    ['TO', 'Tocantins'],
  ],

  bz: [
    ['BZ', 'Belize'],
    ['CY', 'Cayo'],
    ['CZ', 'Corozal'],
    ['OW', 'Orange Walk'],
    ['SC', 'Stann Creek'],
    ['TO', 'Toledo'],
  ],

  ca: [
    ['AB', 'Alberta'],
    ['BC', 'British Columbia'],
    ['MB', 'Manitoba'],
    ['NB', 'New Brunswick'],
    ['NE', 'ACS Legacy'],
    ['NF', 'Newfoundland (old)'],
    ['NL', 'Newfoundland & Labr.'],
    ['NS', 'Nova Scotia'],
    ['NT', 'Northwest Terr.'],
    ['NU', 'Nunavut'],
    ['ON', 'Ontario'],
    ['PE', 'Prince Edward Island'],
    ['PQ', 'ACS Legacy'],
    ['QC', 'Quebec'],
    ['SK', 'Saskatchewan'],
    ['YT', 'Yukon Territory'],
  ],

  ch: [
    ['AG', 'Aargau'],
    ['AI', 'Inner-Rhoden'],
    ['AR', 'Ausser-Rhoden'],
    ['BE', 'Bern'],
    ['BL', 'Basel Land'],
    ['BS', 'Basel Stadt'],
    ['FR', 'Fribourg'],
    ['GE', 'Geneva'],
    ['GL', 'Glarus'],
    ['GR', 'Graubuenden'],
    ['JU', 'Jura'],
    ['LU', 'Lucerne'],
    ['NE', 'Neuchatel'],
    ['NW', 'Nidwalden'],
    ['OW', 'Obwalden'],
    ['SG', 'St. Gallen'],
    ['SH', 'Schaffhausen'],
    ['SO', 'Solothurn'],
    ['SZ', 'Schwyz'],
    ['TG', 'Thurgau'],
    ['TI', 'Ticino'],
    ['UR', 'Uri'],
    ['VD', 'Vaud'],
    ['VS', 'Valais'],
    ['ZG', 'Zug'],
    ['ZH', 'Zurich'],
  ],

  cl: [
    'I - Iquique',
    'II - Antofagasta',
    'III - Copiapo',
    'IV - La Serena',
    'V - Valparaiso',
    'VI - Rancagua',
    'VII - Talca',
    'VIII - Concepción',
    'IX - Temuco',
    'X - Puerto Montt',
    'XI - Coyhaique',
    'XII - Punta Arenas',
    'RM - Santiago',
  ],

  cn: [
    'Beijing',
    'Shanghai',
    'Tianjin',
    'Nei Mongol',
    'Shanxi',
    'Hebei',
    'Liaoning',
    'Jilin',
    'Heilongjiang',
    'Jiangsu',
    'Anhui',
    'Shandong',
    'Zhejiang',
    'Jiangxi',
    'Fujian',
    'Hunan',
    'Hubei',
    'Henan',
    'Guangdong',
    'Hainan',
    'Guangxi',
    'Guizhou',
    'Sichuan',
    'Yunnan',
    'Shaanxi',
    'Gansu',
    'Ningxia',
    'Qinghai',
    'Xinjiang',
    'Xizang',
    'Taiwan',
  ],

  co: [
    'ANTIOQUIA',
    'ATLANTICO',
    'BOGOTA',
    'BOLIVAR',
    'BOYACA',
    'CALDAS',
    'CAQUETA',
    'CAUCA',
    'CESAR',
    'CORDOBA',
    'CUNDINAMARCA',
    'CHOCO',
    'HUILA',
    'LA GUAJIRA',
    'MAGDALENA',
    'META',
    'NARIÑO',
    'NORTE SANTANDER',
    'QUINDIO',
    'RISARALDA',
    'SANTANDER',
    'SUCRE',
    'TOLIMA',
    'VALLE',
    'ARAUCA',
    'CASANARE',
    'PUTUMAYO',
    'SAN ANDRES',
    'AMAZONAS',
    'GUAINIA',
    'GUAVIARE',
    'VAUPES',
    'VICHADA',
  ],

  cz: [
    'Jihocesky',
    'Jihomoravsky',
    'Praha',
    'Severocesky',
    'Severomoravsky',
    'Stredocesky',
    'Vychodocesky',
    'Zapadocesky',
  ],

  de: [
    'Schleswig-Holstein',
    'Hamburg',
    'Lower Saxony',
    'Bremen',
    'Nrth Rhine Westfalia',
    'Hesse',
    'Rhineland Palatinate',
    'Baden-Wurttemberg',
    'Bavaria',
    'Saarland',
    'Berlin',
    'Brandenburg',
    'Mecklenburg-Vorpomm.',
    'Saxony',
    'Saxony-Anhalt',
    'Thuringia',
  ],

  dk: [
    'Copenhagen',
    'Århus amt',
    'Bornholm amt',
    'Frederiksborg amt',
    'Fyn amt',
    'København amt',
    'Nordjylland amt',
    'Ribe amt',
    'Ringkøbing amt',
    'Roskilde amt',
    'Sønderjylland amt',
    'Storstrøm amt',
    'Vejle amt',
    'Vestsjælland amt',
    'Viborg amt',
    'Grønlands amt',
  ],

  es: [
    'Alava',
    'Albacete',
    'Alicante',
    'Almeria',
    'Avila',
    'Badajoz',
    'Baleares',
    'Barcelona',
    'Burgos',
    'Caceres',
    'Cadiz',
    'Castellon',
    'Ciudad Real',
    'Córdoba',
    'La Coruña',
    'Cuenca',
    'Gerona',
    'Granada',
    'Guadalajara',
    'Guipuzcoa',
    'Huelva',
    'Huesca',
    'Jaen',
    'Leon',
    'Lerida',
    'La Rioja',
    'Lugo',
    'Madrid',
    'Malaga',
    'Murcia',
    'Navarra',
    'Orense',
    'Asturias',
    'Palencia',
    'Las Palmas',
    'Pontevedra',
    'Salamanca',
    'Sta. Cruz Tenerife',
    'Cantabria',
    'Segovia',
    'Sevilla',
    'Soria',
    'Tarragona',
    'Teruel',
    'Toledo',
    'Valencia',
    'Valladolid',
    'Vizcaya',
    'Zamora',
    'Zaragoza',
  ],

  fi: [
    'Ahvenanmaa',
    'Etelä-Suomi',
    'Itä-Suomi',
    'Lappi',
    'Länsi-Suomi',
    'Oulu',
  ],

  fr: [
    'Ain',
    'Aisne',
    'Allier',
    'Alpes (Hte-Provence)',
    'Alpes (Hautes)',
    'Alpes-Maritimes',
    'Ardèche',
    'Ardennes',
    'Ariège',
    'Aube',
    'Aude',
    'Aveyron',
    'Bouches-du-Rhône',
    'Calvados',
    'Cantal',
    'Charente',
    'Charente-Maritime',
    'Cher',
    'Corrèze',
    "Côte-d'Or",
    "Côtes-d'Armor",
    'Creuse',
    'Dordogne',
    'Doubs',
    'Drôme',
    'Eure',
    'Eure-et-Loir',
    'Finistère',
    'Corse-du-Sud',
    'Corse-du-Nord',
    'Gard',
    'Garonne (Haute)',
    'Gers',
    'Gironde',
    'Hérault',
    'Ille-et-Vilaine',
    'Indre',
    'Indre-et-Loire',
    'Isère',
    'Jura',
    'Landes',
    'Loir-et-Cher',
    'Loire',
    'Loire (Haute)',
    'Loire-Atlantique',
    'Loiret',
    'Lot',
    'Lot-et-Garonne',
    'Lozère',
    'Maine-et-Loire',
    'Manche',
    'Marne',
    'Marne (Haute)',
    'Mayenne',
    'Meurthe-et-Moselle',
    'Meuse',
    'Morbihan',
    'Moselle',
    'Nièvre',
    'Nord',
    'Oise',
    'Orne',
    'Pas-de-Calais',
    'Puy-de-Dôme',
    'Pyrénées-Atlantiques',
    'Pyrénées (Hautes)',
    'Pyrénées-Orientales',
    'Bas-Rhin',
    'Haut-Rhin',
    'Rhône',
    'Saône (Haute)',
    'Saône-et-Loire',
    'Sarthe',
    'Savoie',
    'Savoie (Haute)',
    'Paris',
    'Seine-Maritime',
    'Seine-et-Marne',
    'Yvelines',
    'Sèvres (Deux)',
    'Somme',
    'Tarn',
    'Tarn-et-Garonne',
    'Var',
    'Vaucluse',
    'Vendée',
    'Vienne',
    'Vienne (Haute)',
    'Vosges',
    'Yonne',
    'Territ.-de-Belfort',
    'Essonne',
    'Hauts-de-Seine',
    'Seine-Saint-Denis',
    'Val-de-Marne',
    "Val-d'Oise",
    'D.O.M.-T.O.M.',
    'Guadeloupe',
    'Martinique',
    'Guyane',
    'Réunion',
    'Saint-Pierre-et-Miq.',
    'Wallis-et-Futuna',
    'Hors-France',
  ],

  gb: [
    ['AM', 'Armagh'],
    ['AR', 'Ards'],
    ['AT', 'Antrim'],
    ['BA', 'Ballymena'],
    ['BB', 'Blackburn'],
    ['BE', 'Bedfordshire'],
    ['BF', 'Bracknell Forest'],
    ['BH', 'Brighton & Hove'],
    ['BK', 'Berkshire'],
    ['BL', 'Belfast'],
    ['BM', 'Bournemouth'],
    ['BN', 'Banbridge'],
    ['BO', 'Borders'],
    ['BP', 'Blackpool'],
    ['BR', 'Bristol'],
    ['BS', 'Bath&NthEstSomerset'],
    ['BU', 'Buckinghamshire'],
    ['BY', 'Ballymoney'],
    ['CA', 'Cambridgeshire'],
    ['CE', 'Central'],
    ['CG', 'Craigavon'],
    ['CH', 'Cheshire'],
    ['CI', 'Coleraine'],
    ['CK', 'Cookstown'],
    ['CL', 'Clwyd'],
    ['CO', 'Cornwall'],
    ['CR', 'Carrickfergus'],
    ['CS', 'Castlereagh'],
    ['CU', 'Cumbria'],
    ['CV', 'Cleveland'],
    ['DB', 'Derbyshire'],
    ['DF', 'Dumfries a. Galloway'],
    ['DG', 'Dungannon'],
    ['DL', 'Darlington'],
    ['DN', 'Down'],
    ['DO', 'Dorset'],
    ['DU', 'Durham'],
    ['DV', 'Devon'],
    ['DY', 'Dyfed'],
    ['ER', 'East Riding'],
    ['ES', 'Essex'],
    ['FI', 'Fife'],
    ['FM', 'Fermanagh'],
    ['GL', 'Gloucestershire'],
    ['GM', 'Greater Manchester'],
    ['GR', 'Grampian'],
    ['GS', 'Sth. Gloucestershire'],
    ['GW', 'Gwent'],
    ['GY', 'Gwynedd'],
    ['HA', 'Hampshire'],
    ['HI', 'Highland'],
    ['HL', 'Halton'],
    ['HR', 'Hartlepool'],
    ['HT', 'Hertfordshire'],
    ['HW', 'Hereford and Worcs.'],
    ['IW', 'Isle of Wight'],
    ['KE', 'Kent'],
    ['KH', 'Kingston-upon-Hull'],
    ['LA', 'Lancashire'],
    ['LC', 'Leicester City'],
    ['LD', 'Londonderry'],
    ['LE', 'Leicestershire'],
    ['LI', 'Lincolnshire'],
    ['LM', 'Limavady'],
    ['LO', 'Greater London'],
    ['LR', 'Larne'],
    ['LS', 'Lisburn'],
    ['LT', 'Lothian'],
    ['LU', 'Luton'],
    ['MA', 'Magherafelt'],
    ['MG', 'Mid Glamorgan'],
    ['MI', 'Middlesbrough'],
    ['MK', 'Milton Keynes'],
    ['MO', 'Moyle'],
    ['MY', 'Merseyside'],
    ['NA', 'Newtownabbey'],
    ['NB', 'Newbury'],
    ['NC', 'Nottingham City'],
    ['ND', 'North Down'],
    ['NE', 'NthEast Lincolnshire'],
    ['NH', 'Northamptonshire'],
    ['NK', 'Norfolk'],
    ['NL', 'North Lincolnshire'],
    ['NM', 'Newry and Mourne'],
    ['NS', 'North Somerset'],
    ['NT', 'Nottinghamshire'],
    ['NU', 'Northumberland'],
    ['OM', 'Omagh'],
    ['OR', 'Orkney'],
    ['OX', 'Oxfordshire'],
    ['PB', 'Peterborough'],
    ['PL', 'Poole'],
    ['PM', 'Portsmouth'],
    ['PO', 'Powys'],
    ['PY', 'Plymouth'],
    ['RD', 'Redcar and Cleveland'],
    ['RE', 'Reading'],
    ['RM', 'Rochester up. Medway'],
    ['RU', 'Rutland'],
    ['SC', 'Strathclyde'],
    ['SD', 'Southend'],
    ['SE', 'East Sussex'],
    ['SG', 'South Glamorgan'],
    ['SH', 'Shropshire'],
    ['SK', 'Suffolk'],
    ['SL', 'Shetland'],
    ['SN', 'Stockton-on-Tees'],
    ['SO', 'Somerset'],
    ['SP', 'Southampton'],
    ['SR', 'Strabane'],
    ['ST', 'Staffordshire'],
    ['SU', 'Slough'],
    ['SW', 'West Sussex'],
    ['SY', 'Surrey'],
    ['TA', 'Tayside'],
    ['TD', 'Thamesdown'],
    ['TH', 'Thurrock'],
    ['TO', 'Torbay'],
    ['TW', 'Tyne and Wear'],
    ['WA', 'Warwickshire'],
    ['WD', 'Windsor & Maidenhead'],
    ['WG', 'West Glamorgan'],
    ['WI', 'Wiltshire'],
    ['WL', 'Western Isles'],
    ['WM', 'West Midlands'],
    ['WO', 'Wokingham'],
    ['WR', 'Wrekin'],
    ['WT', 'Warrington'],
    ['YK', 'York'],
    ['YN', 'North Yorkshire'],
    ['YS', 'South Yorkshire'],
    ['YW', 'West Yorkshire'],
  ],

  gr: [
    'Aitolia kai Akarnan.',
    'Akhaia',
    'Argolis',
    'Arkadhia',
    'Arta',
    'Attiki',
    'Dhodhekanisos',
    'Dhrama',
    'Evritania',
    'Evros',
    'Evvoia',
    'Florina',
    'Fokis',
    'Fthiotis',
    'Grevena',
    'Ilia',
    'Imathia',
    'Ioannina',
    'Iraklion',
    'Kardhitsa',
    'Kastoria',
    'Kavala',
    'Kefallinia',
    'Kerkira',
    'Khalkidhiki',
    'Khania',
    'Khios',
    'Kikladhes',
    'Kilkis',
    'Korinthia',
    'Kozani',
    'Lakonia',
    'Larisa',
    'Lasithi',
    'Lesvos',
    'Levkas',
    'Magnisia',
    'Messinia',
    'Pella',
    'Pieria',
    'Piraievs',
    'Preveza',
    'Rethimni',
    'Rodhopi',
    'Samos',
    'Serrai',
    'Thesprotia',
    'Thessaloniki',
    'Trikala',
    'Voiotia',
    'Xanthi',
    'Zakinthos',
  ],

  hk: [
    ['HK', 'Hong Kong Island'],
    ['KLN', 'Kowloon'],
    ['NT', 'New Territories'],
  ],

  hn: [
    ['AT', 'Atlántida'],
    ['CH', 'Choluteca'],
    ['CL', 'Colón'],
    ['CM', 'Comayagua'],
    ['CP', 'Copán'],
    ['CR', 'Cortés'],
    ['EP', 'El Paraíso'],
    ['FM', 'Francisco Morazán'],
    ['GD', 'Gracias a Dios'],
    ['IB', 'Islas de la Bahía'],
    ['IN', 'Intibucá'],
    ['LE', 'Lempira'],
    ['LP', 'La Paz'],
    ['OC', 'Ocotepeque'],
    ['OL', 'Olancho'],
    ['SB', 'Santa Bárbara'],
    ['VA', 'Valle'],
    ['YO', 'Yoro'],
  ],

  hr: [
    'Bjelovar-Bilogora',
    'Stadt Zagreb',
    'Dubrovnik-Neretva',
    'Istra',
    'Karlovac',
    'Koprivnica-Krizevci',
    'Lika-Senj',
    'Medimurje',
    'Osijek-Baranja',
    'Pozega-Slavonija',
    'Primorje-Gorski Kot.',
    'Sibenik',
    'Sisak-Moslavina',
    'Slavonski',
    'Brod-Posavina',
    'Split-Dalmatia',
    'Varazdin',
    'Virovitica-Podravina',
    'Vukovar-Srijem',
    'Zadar-Knin',
    'Zagreb',
  ],

  hu: [
    'Bacs-Kiskun',
    'Baranya',
    'Bekes',
    'Bekescsaba',
    'Borsod-Abauj-Zemplen',
    'Budapest',
    'Csongrad',
    'Debrecen',
    'Dunaujvaros',
    'Eger',
    'Fejer',
    'Gyor',
    'Gyor-Moson-Sopron',
    'Hajdu-Bihar',
    'Heves',
    'Hodmezovasarhely',
    'Jasz-Nagykun-Szolnok',
    'Kaposvar',
    'Kecskemet',
    'Komarom-Esztergom',
    'Miskolc',
    'Nagykanizsa',
    'Nograd',
    'Nyiregyhaza',
    'Pecs',
    'Pest',
    'Somogy',
    'Sopron',
    'Szabolcs-Szat.-Bereg',
    'Szeged',
    'Szekesfehervar',
    'Szolnok',
    'Szombathely',
    'Tatabanya',
    'Tolna',
    'Vas',
    'Veszprem',
    'Zala',
    'Zalaegerszeg',
  ],

  id: [
    'DKI Jakarta Jakarta',
    'Jawa Barat West Java',
    'Jawa Tengah Central',
    'Jawa Timur East Java',
    'DI Yogyakarta Yogyak',
    'DI Aceh Aceh',
    'Sumatera Utara North',
    'Sumatera Barat West',
    'Riau Riau',
    'Jambi Jambi',
    'Sumatera Selatan Sou',
    'Bengkulu Bengkulu',
    'Lampung Lampung',
    'Kalimantan Selatan S',
    'Kalimantan Barat Wes',
    'Kalimantan Tengah Ce',
    'Kalimantan Timur Eas',
    'Sulawesi Selatan Sou',
    'Sulawesi Tenggara So',
    'Sulawesi Tengah Cent',
    'Sulawesi Utara North',
    'Bali Bali',
    'Nusa Tenggara Barat',
    'Nusa Tenggara Timur',
    'Maluku Maluku',
    'Irian Jaya Irian Jay',
    'Timor Timur East Tim',
  ],

  ie: [
    ['CK', 'Cork'],
    ['CL', 'Clare'],
    ['CV', 'Cavan'],
    ['CW', 'Carlow'],
    ['DB', 'Dublin'],
    ['DG', 'Donegal'],
    ['GW', 'Galway'],
    ['KD', 'Kildare'],
    ['KK', 'Kilkenny'],
    ['KY', 'Kerry'],
    ['LF', 'Longford'],
    ['LI', 'Limerick'],
    ['LM', 'Leitrim'],
    ['LS', 'Laois'],
    ['LT', 'Louth'],
    ['MH', 'Monaghan'],
    ['MT', 'Meath'],
    ['MY', 'Mayo'],
    ['OF', 'Offaly'],
    ['RC', 'Rosscommon'],
    ['SG', 'Sligo'],
    ['TP', 'Tipperary'],
    ['WF', 'Waterford'],
    ['WK', 'Wicklow'],
    ['WM', 'Westmeath'],
    ['WX', 'Wexford'],
  ],

  il: [
    'Central',
    'Haifa',
    'Jerusalem',
    'Northern',
    'Southern',
    'Tel Aviv',
  ],

  in: [
    'Andra Pradesh',
    'Arunachal Pradesh',
    'Assam',
    'Bihar',
    'Goa',
    'Gujarat',
    'Haryana',
    'Himachal Pradesh',
    'Jammu und Kashmir',
    'Karnataka',
    'Kerala',
    'Madhya Pradesh',
    'Maharashtra',
    'Manipur',
    'Megalaya',
    'Mizoram',
    'Nagaland',
    'Orissa',
    'Punjab',
    'Rajasthan',
    'Sikkim',
    'Tamil Nadu',
    'Tripura',
    'Uttar Pradesh',
    'West Bengal',
    'Andaman und Nico.In.',
    'Chandigarh',
    'Dadra und Nagar Hav.',
    'Daman und Diu',
    'Delhi',
    'Lakshadweep',
    'Pondicherry',
    'Pondicherry',
    '',
    '',
  ],

  it: [
    ['AG', 'Agriento'],
    ['AL', 'Alessandria'],
    ['AN', 'Ancona'],
    ['AO', 'Aosta'],
    ['AP', 'Ascoli Piceno'],
    ['AQ', "L'Aquila"],
    ['AR', 'Arezzo'],
    ['AT', 'Asti'],
    ['AV', 'Avellino'],
    ['BA', 'Bari'],
    ['BG', 'Bergamo'],
    ['BI', 'Biella'],
    ['BL', 'Belluno'],
    ['BN', 'Benevento'],
    ['BO', 'Bologna'],
    ['BR', 'Brindisi'],
    ['BS', 'Brescia'],
    ['BZ', 'Bolzano'],
    ['CA', 'Cagliari'],
    ['CB', 'Campobasso'],
    ['CE', 'Caserta'],
    ['CH', 'Chieti'],
    ['CL', 'Caltanisetta'],
    ['CN', 'Cuneo'],
    ['CO', 'Como'],
    ['CR', 'Cremona'],
    ['CS', 'Cosenza'],
    ['CT', 'Catania'],
    ['CZ', 'Catanzaro'],
    ['EN', 'Enna'],
    ['FE', 'Ferrara'],
    ['FG', 'Foggia'],
    ['FI', 'Florence'],
    ['FO', 'Forlì'],
    ['FR', 'Frosinone'],
    ['GE', 'Genova'],
    ['GO', 'Gorizia'],
    ['GR', 'Grosseto'],
    ['IM', 'Imperia'],
    ['IS', 'Isernia'],
    ['KR', 'Crotone'],
    ['LC', 'Lecco'],
    ['LE', 'Lecce'],
    ['LI', 'Livorno'],
    ['LO', 'Lodi'],
    ['LT', 'Latina'],
    ['LU', 'Lucca'],
    ['MC', 'Macerata'],
    ['ME', 'Messina'],
    ['MI', 'Milan'],
    ['MN', 'Mantova'],
    ['MO', 'Modena'],
    ['MS', 'Massa Carrara'],
    ['MT', 'Matera'],
    ['NA', 'Naples'],
    ['NO', 'Novara'],
    ['NU', 'Nuoro'],
    ['OR', 'Oristano'],
    ['PA', 'Palermo'],
    ['PC', 'Piacenza'],
    ['PD', 'Padova'],
    ['PE', 'Pescara'],
    ['PG', 'Perugia'],
    ['PI', 'Pisa'],
    ['PN', 'Pordenone'],
    ['PO', 'Prato'],
    ['PR', 'Parma'],
    ['PS', 'Pesaro'],
    ['PT', 'Pistoia'],
    ['PU', 'Pesaro-Urbino'],
    ['PV', 'Pavia'],
    ['PZ', 'Potenza'],
    ['RA', 'Ravenna'],
    ['RC', 'Reggio Calabria'],
    ['RE', 'Reggio Emilia'],
    ['RG', 'Ragusa'],
    ['RI', 'Rieti'],
    ['RM', 'Rome'],
    ['RN', 'Rimini'],
    ['RO', 'Rovigo'],
    ['RV', 'Rovigo'],
    ['SA', 'Salerno'],
    ['SI', 'Siena'],
    ['SO', 'Sondrio'],
    ['SP', 'La Spezia'],
    ['SR', 'Siracusa'],
    ['SS', 'Sassari'],
    ['SV', 'Savona'],
    ['TA', 'Taranto'],
    ['TE', 'Teramo'],
    ['TN', 'Trento'],
    ['TO', 'Turin'],
    ['TP', 'Trapani'],
    ['TR', 'Terni'],
    ['TS', 'Trieste'],
    ['TV', 'Treviso'],
    ['UD', 'Udine'],
    ['VA', 'Varese'],
    ['VC', 'Vercelli'],
    ['VE', 'Venice'],
    ['VI', 'Vicenza'],
    ['VR', 'Verona'],
    ['VT', 'Viterbo'],
    ['VV', 'Vibo Valentia'],
  ],

  jp: [
    'Hokkaido',
    'Aomori',
    'Iwate',
    'Miyagi',
    'Akita',
    'Yamagata',
    'Fukushima',
    'Ibaraki',
    'Tochigi',
    'Gunma',
    'Saitama',
    'Chiba',
    'Tokyo',
    'Kanagawa',
    'Niigata',
    'Toyama',
    'Ishikawa',
    'Fukui',
    'Yamanashi',
    'Nagano',
    'Gifu',
    'Shizuoka',
    'Aichi',
    'Mie',
    'Shiga',
    'Kyoto',
    'Osaka',
    'Hyogo',
    'Nara',
    'Wakayama',
    'Tottori',
    'Shimane',
    'Okayama',
    'Hiroshima',
    'Yamaguchi',
    'Tokushima',
    'Kagawa',
    'Ehime',
    'Kochi',
    'Fukuoka',
    'Saga',
    'Nagasaki',
    'Kumamoto',
    'Oita',
    'Miyazaki',
    'Kagoshima',
    'Okinawa',
  ],

  kr: [
    'Cheju-do',
    'Cholla-bukto',
    'Cholla-namdo',
    'Ch´ungch´ong-bukto',
    'Ch´ungch´ong-namdo',
    'Inch´on-jikhalsi',
    'Kangwon-do',
    'Kwangju-jikhalsi',
    'Kyonggi-do',
    'Kyongsang-bukto',
    'Kyongsang-namdo',
    'Pusan-jikhalsi',
    'Soul-t´ukpyolsi',
    'Taegu-jikhalsi',
    'Taejon-jikhalsi',
  ],

  kz: [
    'Almatynskaia',
    'Kostanaiskaia',
    'Severo-Kazakhstansk',
    'Pavlodarskaia',
    'Akmolinskaia',
    'Aktubinskaia',
    'Atyrauskaia',
    'Zapadno-Kazakhst',
    'Mangystayskaia',
    'Karagandinskaia',
    'Vostochno-Kazakhstan',
    'Gambilskaia',
    'Kyzilordinskaia',
  ],

  mx: [
    ['AGS', 'Aguascalientes'],
    ['AGU', 'Aguascalientes'],
    ['BCN', 'Baja California (N)'],
    ['BCS', 'Baja California Sur'],
    ['CAM', 'Campeche'],
    ['CHH', 'Chihuahua'],
    ['CHI', 'Chihuahua'],
    ['CHP', 'Chiapas'],
    ['CHS', 'Chiapas'],
    ['CMP', 'Campeche'],
    ['COA', 'Coahuila'],
    ['COL', 'Colima'],
    ['DF', 'Distrito Federal'],
    ['DGO', 'Durango'],
    ['DIF', 'Distrito Federal'],
    ['DUR', 'Durango'],
    ['GRO', 'Guerrero'],
    ['GTO', 'Guanajuato'],
    ['GUA', 'Guanajuato'],
    ['HGO', 'Hidalgo'],
    ['HID', 'Hidalgo'],
    ['JAL', 'Jalisco'],
    ['MCH', 'Michoacán'],
    ['MEX', 'Estado de México'],
    ['MIC', 'Michoacán'],
    ['MOR', 'Morelos'],
    ['NAY', 'Nayarit'],
    ['NL', 'Nuevo Léon'],
    ['NLE', 'Nuevo Léon'],
    ['OAX', 'Oaxaca'],
    ['PUE', 'Puebla'],
    ['QR', 'Quintana Roo'],
    ['QRO', 'Querétaro'],
    ['QUE', 'Querétaro'],
    ['ROO', 'Quintana Roo'],
    ['SIN', 'Sinaloa'],
    ['SLP', 'San Luis Potosí'],
    ['SON', 'Sonora'],
    ['TAB', 'Tabasco'],
    ['TAM', 'Tamaulipas'],
    ['TLA', 'Tlaxcala'],
    ['TLX', 'Tlaxcala'],
    ['TMS', 'Tamaulipas'],
    ['VER', 'Veracruz'],
    ['YUC', 'Yucatán'],
    ['ZAC', 'Zacatecas'],
  ],

  my: [
    ['JOH', 'Johor'],
    ['KED', 'Kedah'],
    ['KEL', 'Kelantan'],
    ['KUL', 'Kuala Lumpur'],
    ['LAB', 'Labuan'],
    ['MEL', 'Melaka'],
    ['PAH', 'Pahang'],
    ['PEL', 'Perlis'],
    ['PER', 'Perak'],
    ['PIN', 'Pulau Pinang'],
    ['SAB', 'Sabah'],
    ['SAR', 'Sarawak'],
    ['SEL', 'Selangor'],
    ['SER', 'Negeri Sembilan'],
    ['TRE', 'Trengganu'],
  ],

  nl: [
    'Drenthe',
    'Flevoland',
    'Friesland',
    'Gelderland',
    'Groningen',
    'Limburg',
    'Noord-Brabant',
    'Noord-Holland',
    'Overijssel',
    'Utrecht',
    'Zeeland',
    'Zuid-Holland',
  ],

  no: [
    'Østfold Fylke',
    'Akershus Fylke',
    'Oslo',
    'Hedmark Fylke',
    'Oppland Fylke',
    'Buskerud Fylke',
    'Vestfold Fylke',
    'Telemark Fylke',
    'Aust-Agder Fylke',
    'Vest-Agder Fylke',
    'Rogaland Fylke',
    'Hordaland Fylke',
    'Sogn og Fjordane F.',
    'Møre og Romsdal F.',
    'Sør-Trøndelag Fylke',
    'Nord-Trøndelag Fylke',
    'Nordland Fylke',
    'Troms Fylke',
    'Finnmark Fylke',
  ],

  nz: [
    ['AKL', 'Auckland'],
    ['BOP', 'Bay of Plenty'],
    ['CAN', 'Canterbury'],
    ['HAB', 'Hawke´s Bay'],
    ['MAN', 'Manawatu-Wanganui'],
    ['NTL', 'Northland'],
    ['OTA', 'Otago'],
    ['STL', 'Southland'],
    ['TAR', 'Taranaki'],
    ['WAI', 'Waikato'],
    ['WEC', 'West Coast'],
    ['WLG', 'Wellington'],
  ],

  pe: [
    'Tumbes',
    'Piura',
    'Lambayeque',
    'La Libertad',
    'Ancash',
    'Lima y Callao',
    'Ica',
    'Arequipa',
    'Moquegua',
    'Tacna',
    'Amazon',
    'Cajamarca',
    'San Martín',
    'Huánuco',
    'Pasco',
    'Junín',
    'Huancavelica',
    'Ayacucho',
    'Apurimac',
    'Cuzco',
    'Puno',
    'Loreto',
    'Ucayali',
    'Madre de Díos',
  ],

  ph: [
    'Ilocos',
    'Cagayan Valley',
    'Central Luzon',
    'South Luzon',
    'Bicol',
    'West Visayas',
    'Central Visayas',
    'Eastern Visayas',
    'Western Mindanao',
    'Northern Mindanao',
    'Central Mindanao',
    'South Mindanao',
  ],

  pl: [
    'Biala Podlaska',
    'Bialystok',
    'Bielsko Biala',
    'Bydgoszcz',
    'Chelm',
    'Ciechanow',
    'Czestochowa',
    'Elblag',
    'Gdansk',
    'Gorzow',
    'Jelenia Gora',
    'Kalisz',
    'Katowice',
    'Kielce',
    'Konin',
    'Koszalin',
    'Krakow',
    'Krosno',
    'Legnica',
    'Leszno',
    'Lodz',
    'Lomza',
    'Lublin',
    'Nowy Sacz',
    'Olsztyn',
    'Opole',
    'Ostroleka',
    'Pila',
    'Piotrkow',
    'Plock',
    'Poznan',
    'Przemysl',
    'Radom',
    'Rzeszow',
    'Siedlce',
    'Sieradz',
    'Skierniewice',
    'Slupsk',
    'Suwalki',
    'Szczecin',
    'Tarnobrzeg',
    'Tarnow',
    'Torun',
    'Walbrzych',
    'Warszawa',
    'Wloclawek',
    'Wroclaw',
    'Zamosc',
    'Zielona Gora',
  ],

  pt: [
    'Minho-Lima',
    'Cávado',
    'Ave',
    'Grande Porto',
    'Tâmega',
    'Entre Douro e Vouga',
    'Douro',
    'Alto Trás-os-Montes',
    'Baixo Vouga',
    'Baixo Mondego',
    'Pinhal Litoral',
    'Pinhal Interior N.',
    'Pinhal Interior Sul',
    'Dão-Lafoes',
    'Serra da Estrela',
    'Beira Interior Norte',
    'Beira Interior Sul',
    'Cova da Beira',
    'Oeste',
    'Grande Lisboa',
    'Península de Setúbal',
    'Médio Tejo',
    'Lezíria do Tejo',
    'Alentejo Litoral',
    'Alto Alentejo',
    'Alentejo Central',
    'Baixo Alentejo',
    'Algarve',
    'Reg. Aut. dos Açores',
    'Reg. Aut. da Madeira',
  ],

  ro: [
    'Alba',
    'Arad',
    'Arges',
    'Bacau',
    'Bihor',
    'Bistrita-Nasaud',
    'Botosani',
    'Braila',
    'Brasov',
    'Bucuresti',
    'Buzau',
    'Calarasi',
    'Caras-Severin',
    'Cluj',
    'Constanta',
    'Covasna',
    'Dimbovita',
    'Dolj',
    'Galati',
    'Gorj',
    'Giurgiu',
    'Harghita',
    'Hunedoara',
    'Ialomita',
    'Iasi',
    'Maramures',
    'Mehedinti',
    'Mures',
    'Neamt',
    'Olt',
    'Prahova',
    'Salaj',
    'Satu Mare',
    'Sibiu',
    'Suceava',
    'Teleorman',
    'Timis',
    'Tulcea',
    'Vaslui',
    'Vilcea',
    'Vrancea',
  ],

  ru: [
    'Adigeja Republic',
    'Highlands-Altay Rep.',
    'Republ.of Bashkortos',
    'Buryat Republic',
    'Dagestan Republic',
    'Ingushetija Republic',
    'Kabardino-Balkar.Rep',
    'Kalmyk Republic',
    'Karach.-Cherkessk Re',
    'Karelian Republic',
    'Komi Republic',
    'Marijskaya Republic',
    'Mordovian Republic',
    'Yakutiya-Saha Rrepub',
    'North-Osetiya Republ',
    'Tatarstan Republic',
    'Tuva Republic',
    'The Udmurt Republic',
    'Chakassky Republic',
    'Chechenskaya Republ.',
    'Chuvash Republic',
    'Altay Territory',
    'Krasnodar Territory',
    'Krasnoyarsk Territor',
    'Primorye Territory',
    'Stavropol Territory',
    'Khabarovsk Territory',
    'The Amur Area',
    'The Arkhangelsk Area',
    'The Astrakhan Area',
    'The Belgorod Area',
    'The Bryansk Area',
    'The Vladimir Area',
    'The Volgograd Area',
    'The Vologda Area',
    'The Voronezh Area',
    'The Ivanovo Area',
    'The Irkutsk Area',
    'The Kaliningrad Area',
    'The Kaluga Area',
    'The Kamchatka Area',
    'The Kemerovo Area',
    'The Kirov Area',
    'The Kostroma Area',
    'The Kurgan Area',
    'The Kursk Area',
    'The Leningrad Area',
    'The Lipetsk Area',
    'The Magadan Area',
    'The Moscow Area',
    'The Murmansk Area',
    'The Nizhniy Novgorod',
    'The Novgorod Area',
    'The Novosibirsk Area',
    'The Omsk Area',
    'The Orenburg Area',
    'The Oryol Area',
    'The Penza Area',
    'The Perm Area',
    'The Pskov Area',
    'The Rostov Area',
    'The Ryazan Area',
    'The Samara Area',
    'The Saratov Area',
    'The Sakhalin Area',
    'The Sverdlovsk Area',
    'The Smolensk Area',
    'The Tambov Area',
    'The Tver Area',
    'The Tomsk Area',
    'The Tula Area',
    'The Tyumen Area',
    'The Ulyanovsk Area',
    'The Chelyabinsk Area',
    'The Chita Area',
    'The Yaroslavl Area',
    'c.Moscow',
    'c.St-Peterburg',
    'The Jewish Auton.are',
    'Aginsk Buryat Aut.di',
    'Komy Permjats.Aut.di',
    'Korjacs Auton.distri',
    'Nenekchky Auton.dist',
    'The Taymir Auton.dis',
    'Ust-Ordinsky Buryat',
    'Chanti-Mansyjsky Aut',
    'Chukotka Auton. dist',
    'Evensky Auton.distri',
    'Jamalo-Nenekchky Aut',
  ],

  se: [
    'Blekinge Län',
    'Dalarnas Län',
    'Gotlands Län',
    'Gävleborgs Län',
    'Hallands Län',
    'Jämtlands Län',
    'Jönköpings Län',
    'Kalmar Län',
    'Kronobergs Län',
    'Norrbottens Län',
    'Skåne Län',
    'Stockholms Län',
    'Södermanlands Län',
    'Uppsala Län',
    'Värmlands Län',
    'Västerbottens Län',
    'Västernorrlands Län',
    'Västmanlands Län',
    'Västra Götalands Län',
    'Örebro Län',
    'Östergötlands Län',
  ],

  sg: [
    ['SG', 'Singapore'],
  ],

  si: [
    'Ajdovscina',
    'Brezice',
    'Celje',
    'Cerknica',
    'Crnomelj',
    'Dravograd',
    'Gornja Radgona',
    'Grosuplje',
    'Hrastnik Lasko',
    'Idrija',
    'Ilirska Bistrica',
    'Izola',
    'Jesenice',
    'Kamnik',
    'Kocevje',
    'Koper',
    'Kranj',
    'Krsko',
    'Lenart',
    'Lendava',
    'Litija',
    'Ljubljana-Bezigrad',
    'Ljubljana-Center',
    'Ljubljana-Moste-Polj',
    'Ljubljana-Siska',
    'Ljubljana-Vic-Rudnik',
    'Ljutomer',
    'Logatec',
    'Maribor',
    'Metlika',
    'Mozirje',
    'Murska Sobota',
    'Nova Gorica',
    'Novo Mesto',
    'Ormoz',
    'Pesnica',
    'Piran',
    'Postojna',
    'Ptuj',
    'Radlje Ob Dravi',
    'Radovljica',
    'Ravne Na Koroskem',
    'Ribnica',
    'Ruse',
    'Sentjur Pri Celju',
    'Sevnica',
    'Sezana',
    'Skofja Loka',
    'Slovenj Gradec',
    'Slovenska Bistrica',
    'Slovenske Konjice',
    'Smarje Pri Jelsah',
    'Tolmin',
    'Trbovlje',
    'Trebnje',
    'Trzic',
    'Velenje',
    'Vrhnika',
    'Zagorje Ob Savi',
    'Zalec',
  ],

  sk: [
    'Bratislava',
    'Zapadoslovensky',
    'Stredoslovensky',
    'Vychodoslovensky',
  ],

  th: [
    'Amnat Charoen',
    'Ang Thong',
    'Buriram',
    'Chachoengsao',
    'Chai Nat',
    'Chaiyaphum',
    'Chanthaburi',
    'Chiang Mai',
    'Chiang Rai',
    'Chon Buri',
    'Chumphon',
    'Kalasin',
    'Kamphaeng Phet',
    'Kanchanaburi',
    'Khon Kaen',
    'Krabi',
    'Krung Thep',
    'Mahanakhon',
    'Lampang',
    'Lamphun',
    'Loei',
    'Lop Buri',
    'Mae Hong Son',
    'Maha Sarakham',
    'Mukdahan',
    'Nakhon Nayok',
    'Nakhon Pathom',
    'Nakhon Phanom',
    'Nakhon Ratchasima',
    'Nakhon Sawan',
    'Nakhon Si Thammarat',
    'Nan',
    'Narathiwat',
    'Nong Bua Lamphu',
    'Nong Khai',
    'Nonthaburi',
    'Pathum Thani',
    'Pattani',
    'Phangnga',
    'Phatthalung',
    'Phayao',
    'Phetchabun',
    'Phetchaburi',
    'Phichit',
    'Phitsanulok',
    'Phra Nakhon Si Ayut.',
    'Phrae',
    'Phuket',
    'Prachin Buri',
  ],

  tr: [
    'Adana',
    'Adiyaman',
    'Afyon',
    'Agri',
    'Amasya',
    'Ankara',
    'Antalya',
    'Artvin',
    'Aydin',
    'Balikesir',
    'Bilecik',
    'Bingöl',
    'Bitlis',
    'Bolu',
    'Burdur',
    'Bursa',
    'Canakkale',
    'Cankiri',
    'Corum',
    'Denizli',
    'Diyarbakir',
    'Edirne',
    'Elazig',
    'Erzincan',
    'Erzurum',
    'Eskisehir',
    'Gaziantep',
    'Giresun',
    'Gümüshane',
    'Hakkari',
    'Hatay',
    'Isparta',
    'Icel',
    'Istanbul',
    'Izmir',
    'Kars',
    'Kastamonu',
    'Kayseri',
    'Kirklareli',
    'Kirshehir',
    'Kocaeli',
    'Konya',
    'Kütahya',
    'Malatya',
    'Manisa',
    'K.Marash',
    'Mardin',
    'Mugla',
    'Mush',
    'Nevshehir',
    'Nigde',
    'Ordu',
    'Rize',
    'Sakarya',
    'Samsun',
    'Siirt',
    'Sinop',
    'Sivas',
    'Tekirdag',
    'Tokat',
    'Trabzon',
    'Tunceli',
    'Shanliurfa',
    'Ushak',
    'Van',
    'Yozgat',
    'Zonguldak',
    'Aksaray',
    'Bayburt',
    'Karaman',
    'Kirikkale',
    'Batman',
    'Shirnak',
    'Bartin',
    'Ardahan',
    'Igdir',
    'Yalova',
  ],

  tw: [
    ['FJN', 'Fu-chien'],
    ['KSH', 'Kao-hsiung'],
    ['TPE', 'T´ai-pei'],
    ['TWN', 'Taiwan'],
  ],

  ua: [
    ['CHG', "Chernigivs'ka"],
    ['CHR', "Cherkas'ka"],
    ['CHV', "Chernovits'ka"],
    ['DNP', "Dnipropetrovs'ka"],
    ['DON', "Donets'ka"],
    ['HAR', "Harkivs'ka"],
    ['HML', "Hmel'nits'ka"],
    ['HRS', "Hersons'ka"],
    ['IVF', "Ivano-Frankivs'ka"],
    ['KIE', "Kievs'ka"],
    ['KIR', "Kirovograds'ka"],
    ['KRM', 'Respublika Krim'],
    ['LUG', "Lugans'ka"],
    ["L'V", "L'vivsbka"],
    ['M_K', 'm.Kiev'],
    ['M_S', "m.Sevastopil'"],
    ['MIK', "Mikolaivs'ka"],
    ['ODS', "Odes'ka"],
    ['POL', "Poltavs'ka"],
    ['RIV', "Rivnens'ka"],
    ['SUM', "Sums'ka"],
    ['TER', "Ternopil's'ka"],
    ['VIN', "Vinnits'ka"],
    ['VOL', "Volins'ka"],
    ['ZAK', "Zakarpats'ka"],
    ['ZAP', "Zaporiz'ka"],
    ['ZHI', "Zhitomirs'ka"],
  ],

  us: [
    ['AA', 'Armed Forces America'],
    ['AE', 'Armed Forces Europe'],
    ['AK', 'Alaska'],
    ['AL', 'Alabama'],
    ['AP', 'Armed Forces Pacific'],
    ['AR', 'Arkansas'],
    ['AS', 'American Samoa'],
    ['AZ', 'Arizona'],
    ['CA', 'California'],
    ['CO', 'Colorado'],
    ['CT', 'Connecticut'],
    ['DC', 'District of Columbia'],
    ['DE', 'Delaware'],
    ['FL', 'Florida'],
    ['GA', 'Georgia'],
    ['GU', 'Guam'],
    ['HI', 'Hawaii'],
    ['IA', 'Iowa'],
    ['ID', 'Idaho'],
    ['IL', 'Illinois'],
    ['IN', 'Indiana'],
    ['KS', 'Kansas'],
    ['KY', 'Kentucky'],
    ['LA', 'Louisiana'],
    ['MA', 'Massachusetts'],
    ['MD', 'Maryland'],
    ['ME', 'Maine'],
    ['MI', 'Michigan'],
    ['MN', 'Minnesota'],
    ['MO', 'Missouri'],
    ['MP', 'Northern Mariana Isl'],
    ['MS', 'Mississippi'],
    ['MT', 'Montana'],
    ['NC', 'North Carolina'],
    ['ND', 'North Dakota'],
    ['NE', 'Nebraska'],
    ['NH', 'New Hampshire'],
    ['NJ', 'New Jersey'],
    ['NM', 'New Mexico'],
    ['NP', 'No Plate'],
    ['NV', 'Nevada'],
    ['NY', 'New York'],
    ['OH', 'Ohio'],
    ['OK', 'Oklahoma'],
    ['OR', 'Oregon'],
    ['PA', 'Pennsylvania'],
    ['PP', 'Paper Plate'],
    ['PR', 'Puerto Rico'],
    ['RI', 'Rhode Island'],
    ['SC', 'South Carolina'],
    ['SD', 'South Dakota'],
    ['TN', 'Tennessee'],
    ['TX', 'Texas'],
    ['UT', 'Utah'],
    ['VA', 'Virginia'],
    ['VI', 'Virgin Islands'],
    ['VT', 'Vermont'],
    ['WA', 'Washington'],
    ['WI', 'Wisconsin'],
    ['WV', 'West Virginia'],
    ['WY', 'Wyoming'],
  ],

  ve: [
    ['AMA', 'Amazon'],
    ['ANZ', 'Anzoategui'],
    ['APU', 'Apure'],
    ['ARA', 'Aragua'],
    ['BAR', 'Barinas'],
    ['BOL', 'Bolivar'],
    ['CAR', 'Carabobo'],
    ['COJ', 'Cojedes'],
    ['DA', 'Delta Amacuro'],
    ['DF', 'Distrito Federal'],
    ['FAL', 'Falcon'],
    ['GUA', 'Guarico'],
    ['LAR', 'Lara'],
    ['MER', 'Merida'],
    ['MIR', 'Miranda'],
    ['MON', 'Monagas'],
    ['NE', 'Nueva Esparta'],
    ['POR', 'Portuguesa'],
    ['SUC', 'Sucre'],
    ['TAC', 'Tachira'],
    ['TRU', 'Trujillo'],
    ['VAR', 'Vargas'],
    ['YAR', 'Yaracuy'],
    ['ZUL', 'Zulia'],
  ],

  za: [
    ['EC', 'Eastern Cape'],
    ['FS', 'Freestate'],
    ['GP', 'Gauteng'],
    ['KZN', 'Kwazulu/Natal'],
    ['MP', 'Mpumalanga'],
    ['NC', 'Northern Cape'],
    ['NP', 'Northern Province'],
    ['NW', 'North-West'],
    ['WC', 'Western Cape'],
  ],
};

const cmp = (a, b) => {
  if (a > b) {
    return 1;
  }
  if (a < b) {
    return -1;
  }
  return 0;
};

const countryCodes = {};
countries.forEach(([iso, name]) => { countryCodes[iso] = name; });

export const StateMenu = ({ country, onChange, ...props }) => {
  const groups = useMemo(() => {
    let xcountries = [];
    if (country === null || country === undefined || country === '') {
      xcountries = ['us', 'ca', 'mx'];
    } else if (Array.isArray(country)) {
      if (country.length === 0) {
        xcountries = ['us', 'ca', 'mx'];
      } else {
        xcountries = country.slice();
      }
    } else {
      xcountries = [country];
    }
    return xcountries.filter((ctry) => states[ctry] && states[ctry].length > 1)
      .map((ctry) => ({
        label: countryCodes[ctry],
        options: states[ctry].sort((a, b) => {
          if (typeof a === 'string') {
            return cmp(a, b);
          }
          return cmp(a[1], b[1]);
        }),
      }));
  }, [country]);
  const callback = useMemo(() => {
    if (!onChange) {
      return null;
    }
    return (val) => onChange(Array.isArray(val) ? val[0] : val);
  }, [onChange]);
  if (groups.length === 0) {
    return <StringInput onChange={onChange} {...props} />;
  }
  if (groups.length === 1) {
    return <MenuInput options={groups[0].options} onChange={callback} empty {...props} />;
  }
  return <MenuInput groups={groups} onChange={callback} empty {...props} />;
};

export default StateMenu;
