language: go

sudo: false

go:
  - 1.7

branches:
  only:
    - master

install:
  - go get github.com/miekg/dns
  - go get github.com/gongo/text-parameters
  - go get github.com/DHowett/go-plist
  - go get github.com/mattn/goveralls

script:
  - go test -covermode=count -coverprofile=profile.cov
  - $HOME/gopath/bin/goveralls -coverprofile=profile.cov -service=travis-ci
