// Code generated by protoc-gen-go. DO NOT EDIT.
// source: playlist.proto

package itunespb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Playlist struct {
	Master               *bool       `protobuf:"varint,1,opt,name=master" json:"master,omitempty"`
	PlaylistId           *int32      `protobuf:"varint,2,opt,name=playlist_id,json=playlistId" json:"playlist_id,omitempty"`
	PersistentId         *uint64     `protobuf:"varint,3,opt,name=persistent_id,json=persistentId" json:"persistent_id,omitempty"`
	AllItems             *bool       `protobuf:"varint,4,opt,name=all_items,json=allItems" json:"all_items,omitempty"`
	Visible              *bool       `protobuf:"varint,5,opt,name=visible" json:"visible,omitempty"`
	Name                 *string     `protobuf:"bytes,6,opt,name=name" json:"name,omitempty"`
	DistinguishedKind    *int32      `protobuf:"varint,7,opt,name=distinguished_kind,json=distinguishedKind" json:"distinguished_kind,omitempty"`
	Music                *bool       `protobuf:"varint,8,opt,name=music" json:"music,omitempty"`
	SmartInfo            []byte      `protobuf:"bytes,9,opt,name=smart_info,json=smartInfo" json:"smart_info,omitempty"`
	SmartCriteria        []byte      `protobuf:"bytes,10,opt,name=smart_criteria,json=smartCriteria" json:"smart_criteria,omitempty"`
	Movies               *bool       `protobuf:"varint,11,opt,name=movies" json:"movies,omitempty"`
	TvShows              *bool       `protobuf:"varint,12,opt,name=tv_shows,json=tvShows" json:"tv_shows,omitempty"`
	Podcasts             *bool       `protobuf:"varint,13,opt,name=podcasts" json:"podcasts,omitempty"`
	Audiobooks           *bool       `protobuf:"varint,14,opt,name=audiobooks" json:"audiobooks,omitempty"`
	PurchasedMusic       *bool       `protobuf:"varint,15,opt,name=purchased_music,json=purchasedMusic" json:"purchased_music,omitempty"`
	Folder               *bool       `protobuf:"varint,16,opt,name=folder" json:"folder,omitempty"`
	ParentPersistentId   *uint64     `protobuf:"varint,17,opt,name=parent_persistent_id,json=parentPersistentId" json:"parent_persistent_id,omitempty"`
	GeniusTrackId        *uint64     `protobuf:"varint,18,opt,name=genius_track_id,json=geniusTrackId" json:"genius_track_id,omitempty"`
	Children             []*Playlist `protobuf:"bytes,19,rep,name=children" json:"children,omitempty"`
	Items                []uint64    `protobuf:"varint,20,rep,name=items" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Playlist) Reset()         { *m = Playlist{} }
func (m *Playlist) String() string { return proto.CompactTextString(m) }
func (*Playlist) ProtoMessage()    {}
func (*Playlist) Descriptor() ([]byte, []int) {
	return fileDescriptor_073b59cb25aac063, []int{0}
}

func (m *Playlist) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Playlist.Unmarshal(m, b)
}
func (m *Playlist) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Playlist.Marshal(b, m, deterministic)
}
func (m *Playlist) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Playlist.Merge(m, src)
}
func (m *Playlist) XXX_Size() int {
	return xxx_messageInfo_Playlist.Size(m)
}
func (m *Playlist) XXX_DiscardUnknown() {
	xxx_messageInfo_Playlist.DiscardUnknown(m)
}

var xxx_messageInfo_Playlist proto.InternalMessageInfo

func (m *Playlist) GetMaster() bool {
	if m != nil && m.Master != nil {
		return *m.Master
	}
	return false
}

func (m *Playlist) GetPlaylistId() int32 {
	if m != nil && m.PlaylistId != nil {
		return *m.PlaylistId
	}
	return 0
}

func (m *Playlist) GetPersistentId() uint64 {
	if m != nil && m.PersistentId != nil {
		return *m.PersistentId
	}
	return 0
}

func (m *Playlist) GetAllItems() bool {
	if m != nil && m.AllItems != nil {
		return *m.AllItems
	}
	return false
}

func (m *Playlist) GetVisible() bool {
	if m != nil && m.Visible != nil {
		return *m.Visible
	}
	return false
}

func (m *Playlist) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Playlist) GetDistinguishedKind() int32 {
	if m != nil && m.DistinguishedKind != nil {
		return *m.DistinguishedKind
	}
	return 0
}

func (m *Playlist) GetMusic() bool {
	if m != nil && m.Music != nil {
		return *m.Music
	}
	return false
}

func (m *Playlist) GetSmartInfo() []byte {
	if m != nil {
		return m.SmartInfo
	}
	return nil
}

func (m *Playlist) GetSmartCriteria() []byte {
	if m != nil {
		return m.SmartCriteria
	}
	return nil
}

func (m *Playlist) GetMovies() bool {
	if m != nil && m.Movies != nil {
		return *m.Movies
	}
	return false
}

func (m *Playlist) GetTvShows() bool {
	if m != nil && m.TvShows != nil {
		return *m.TvShows
	}
	return false
}

func (m *Playlist) GetPodcasts() bool {
	if m != nil && m.Podcasts != nil {
		return *m.Podcasts
	}
	return false
}

func (m *Playlist) GetAudiobooks() bool {
	if m != nil && m.Audiobooks != nil {
		return *m.Audiobooks
	}
	return false
}

func (m *Playlist) GetPurchasedMusic() bool {
	if m != nil && m.PurchasedMusic != nil {
		return *m.PurchasedMusic
	}
	return false
}

func (m *Playlist) GetFolder() bool {
	if m != nil && m.Folder != nil {
		return *m.Folder
	}
	return false
}

func (m *Playlist) GetParentPersistentId() uint64 {
	if m != nil && m.ParentPersistentId != nil {
		return *m.ParentPersistentId
	}
	return 0
}

func (m *Playlist) GetGeniusTrackId() uint64 {
	if m != nil && m.GeniusTrackId != nil {
		return *m.GeniusTrackId
	}
	return 0
}

func (m *Playlist) GetChildren() []*Playlist {
	if m != nil {
		return m.Children
	}
	return nil
}

func (m *Playlist) GetItems() []uint64 {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
	proto.RegisterType((*Playlist)(nil), "itunespb.Playlist")
}

func init() { proto.RegisterFile("playlist.proto", fileDescriptor_073b59cb25aac063) }

var fileDescriptor_073b59cb25aac063 = []byte{
	// 427 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x92, 0xdd, 0x8e, 0xd3, 0x30,
	0x10, 0x85, 0x15, 0xfa, 0xb3, 0xe9, 0xf4, 0x8f, 0x1d, 0xaa, 0x95, 0x59, 0x04, 0x44, 0x20, 0x20,
	0x37, 0x54, 0x88, 0x57, 0xe0, 0xaa, 0x42, 0x48, 0xab, 0xc0, 0x7d, 0xe4, 0xc6, 0xee, 0x76, 0xd4,
	0xc4, 0x8e, 0x3c, 0x4e, 0x11, 0x2f, 0xc1, 0x33, 0xa3, 0xd8, 0xcd, 0xb2, 0x7b, 0x97, 0xf3, 0x9d,
	0x23, 0xc7, 0x9e, 0x33, 0xb0, 0x6a, 0x6b, 0xf9, 0xa7, 0x26, 0xf6, 0xdb, 0xd6, 0x59, 0x6f, 0x31,
	0x25, 0xdf, 0x19, 0xcd, 0xed, 0xfe, 0x76, 0xee, 0x9d, 0xac, 0x4e, 0x11, 0xbf, 0xfb, 0x3b, 0x81,
	0xf4, 0xee, 0x92, 0xc4, 0x1b, 0x98, 0x36, 0x92, 0xbd, 0x76, 0x22, 0xc9, 0x92, 0x3c, 0x2d, 0x2e,
	0x0a, 0xdf, 0xc2, 0x7c, 0x38, 0xad, 0x24, 0x25, 0x9e, 0x65, 0x49, 0x3e, 0x29, 0x60, 0x40, 0x3b,
	0x85, 0xef, 0x61, 0xd9, 0x6a, 0xc7, 0xc4, 0x5e, 0x9b, 0x10, 0x19, 0x65, 0x49, 0x3e, 0x2e, 0x16,
	0xff, 0xe1, 0x4e, 0xe1, 0x2b, 0x98, 0xc9, 0xba, 0x2e, 0xc9, 0xeb, 0x86, 0xc5, 0x38, 0xfc, 0x20,
	0x95, 0x75, 0xbd, 0xeb, 0x35, 0x0a, 0xb8, 0x3a, 0x13, 0xd3, 0xbe, 0xd6, 0x62, 0x12, 0xac, 0x41,
	0x22, 0xc2, 0xd8, 0xc8, 0x46, 0x8b, 0x69, 0x96, 0xe4, 0xb3, 0x22, 0x7c, 0xe3, 0x67, 0x40, 0x45,
	0xec, 0xc9, 0xdc, 0x77, 0xc4, 0x47, 0xad, 0xca, 0x13, 0x19, 0x25, 0xae, 0xc2, 0xbd, 0xae, 0x9f,
	0x38, 0xdf, 0xc9, 0x28, 0xdc, 0xc0, 0xa4, 0xe9, 0x98, 0x2a, 0x91, 0x86, 0xa3, 0xa3, 0xc0, 0xd7,
	0x00, 0xdc, 0x48, 0xe7, 0x4b, 0x32, 0x07, 0x2b, 0x66, 0x59, 0x92, 0x2f, 0x8a, 0x59, 0x20, 0x3b,
	0x73, 0xb0, 0xf8, 0x01, 0x56, 0xd1, 0xae, 0x1c, 0x79, 0xed, 0x48, 0x0a, 0x08, 0x91, 0x65, 0xa0,
	0xdf, 0x2e, 0x30, 0xcc, 0xcc, 0x9e, 0x49, 0xb3, 0x98, 0x5f, 0x66, 0x16, 0x14, 0xbe, 0x84, 0xd4,
	0x9f, 0x4b, 0x3e, 0xda, 0xdf, 0x2c, 0x16, 0xf1, 0x45, 0xfe, 0xfc, 0xb3, 0x97, 0x78, 0x0b, 0x69,
	0x6b, 0x55, 0x25, 0xd9, 0xb3, 0x58, 0xc6, 0x39, 0x0c, 0x1a, 0xdf, 0x00, 0xc8, 0x4e, 0x91, 0xdd,
	0x5b, 0x7b, 0x62, 0xb1, 0x0a, 0xee, 0x23, 0x82, 0x9f, 0x60, 0xdd, 0x76, 0xae, 0x3a, 0x4a, 0xd6,
	0xaa, 0x8c, 0x8f, 0x5a, 0x87, 0xd0, 0xea, 0x01, 0xff, 0x08, 0xaf, 0xbb, 0x81, 0xe9, 0xc1, 0xd6,
	0x4a, 0x3b, 0xf1, 0x3c, 0xde, 0x2b, 0x2a, 0xfc, 0x02, 0x9b, 0x56, 0xba, 0xbe, 0xa6, 0xa7, 0x8d,
	0x5d, 0x87, 0xc6, 0x30, 0x7a, 0x77, 0x8f, 0x7b, 0xfb, 0x08, 0xeb, 0x7b, 0x6d, 0xa8, 0xe3, 0x32,
	0x2c, 0x4e, 0x1f, 0xc6, 0x10, 0x5e, 0x46, 0xfc, 0xab, 0xa7, 0x3b, 0x85, 0x5b, 0x48, 0xab, 0x23,
	0xd5, 0xca, 0x69, 0x23, 0x5e, 0x64, 0xa3, 0x7c, 0xfe, 0x15, 0xb7, 0xc3, 0xd2, 0x6d, 0x87, 0x1d,
	0x2b, 0x1e, 0x32, 0x7d, 0x2b, 0x71, 0x17, 0x36, 0xd9, 0x28, 0x1f, 0x17, 0x51, 0xfc, 0x0b, 0x00,
	0x00, 0xff, 0xff, 0x6b, 0x01, 0x25, 0xd3, 0xb8, 0x02, 0x00, 0x00,
}
